name: Deploy to Heroku

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install
        run: npm install
      - name: build
        run: npm run build:full

  deploy:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ''
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - name: set remote
        run: heroku git:remote -a ${{secrets.HEROKU_APP_NAME}}
      - name: push
        run: git subtree push -f --prefix backend heroku master
